spring.application.name=kino2
# Adres URL do bazy danych w XAMPP (localhost, domyślny port 3306 i nazwa naszej bazy)
spring.datasource.url=jdbc:mysql://localhost:3306/kino_db?useSSL=false&serverTimezone=UTC

# Domyślny użytkownik i hasło w XAMPP
spring.datasource.username=root
spring.datasource.password=

# Magiczna linijka: update oznacza, że Spring sam stworzy/zaktualizuje tabele na podstawie klas w Javie
spring.jpa.hibernate.ddl-auto=update

# Pokazuj w konsoli IntelliJ prawdziwe zapytania SQL, które Spring wysyła do bazy (genialne do nauki!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true